# Generated by Django 3.1.2 on 2020-12-14 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.CharField(max_length=500)),
                ('image', models.CharField(max_length=500)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
