# Generated by Django 3.1.2 on 2020-12-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_bids_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='itemBid',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.Auction'),
        ),
    ]
