# Generated by Django 3.1.2 on 2020-12-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_bids_itembid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bids',
            name='itemBid',
        ),
        migrations.AddField(
            model_name='auction',
            name='itemBid',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.Bids'),
        ),
    ]
