# Generated by Django 3.1.2 on 2020-12-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20201224_0024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='itemBid',
        ),
        migrations.AddField(
            model_name='bids',
            name='itemBid',
            field=models.ManyToManyField(blank=True, related_name='bids', to='auctions.Auction'),
        ),
    ]
