# Generated by Django 3.1.2 on 2020-12-30 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auto_20201230_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='winner',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
