# Generated by Django 3.1.2 on 2021-01-01 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auction_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='auction',
            field=models.ManyToManyField(blank=True, related_name='comments', to='auctions.Auction'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='comment',
            field=models.CharField(max_length=650),
        ),
    ]
