# Generated by Django 3.1.2 on 2021-01-01 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_auto_20210101_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='user',
            field=models.CharField(default='', max_length=80),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auction',
            name='owner',
            field=models.CharField(max_length=80),
        ),
    ]
